import {cleanTraining,priorTraining,compareTraining} from './training.js';
import {dateKey,localTime,initialState,isTime,adherence,planned,completed,planAt,validateState} from './core.js';
import {openDB,readState,writeState,saveBackupTime} from './db.js';
import {prepareBackup,canSaveViaShare,sharePreparedFile} from './backup.js';
import {photoData,cachedPhotoData} from './photo-data.js';
const $=s=>document.querySelector(s),app=$('#app');
const viewNames={front:'正面',side:'側面',back:'背面'},typeNames={quick:'夕食前の簡易運動',strength:'筋トレ'},dayNames=['日','月','火','水','木','金','土'];
let state,tab='home',stream=null,draft=null,photoView='front',compareIds=[],urls=[],busy=false,timer=null,cameraToken=0;
let preparedBackup=null,backupDownloadURL=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=at=>at.replace('T',' ').replaceAll('-','/');
const photoURL=p=>{const data=cachedPhotoData(p.blob);if(data)return data;const url=URL.createObjectURL(p.blob);urls.push(url);return url;};
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>$('#toast').style.display='none',6000);}
function stopCamera(){cameraToken++;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;clearInterval(timer);timer=null;}
async function guarded(task){if(busy)return;busy=true;try{await task();}catch(e){console.error(e);toast(e.name==='QuotaExceededError'?'端末の保存容量が足りません。バックアップを取り、不要な写真を削除してください。':e.message||'処理を完了できませんでした。');}finally{busy=false;}}
async function commit(change){const run=async()=>{const current=await readState();const next=await change(current);state=await writeState(next);clearPreparedBackup();};if(navigator.locks)await navigator.locks.request('body-recomp-write',run);else await run();render();}
function connection(){ $('#connection').textContent=navigator.onLine?'端末内保存':'オフライン'; }
function render(){urls.forEach(URL.revokeObjectURL);urls=[];document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false');});({home:homeScreen,measure:measureScreen,photos:photosScreen,exercise:exerciseScreen,settings:settingsScreen}[tab])();connection();}
function title(eyebrow,heading,description=''){return `<div class="eyebrow">${eyebrow}</div><h1>${heading}</h1>${description?`<p class="muted">${description}</p>`:''}`;}
function metric(name,key,unit){const latest=[...state.measurements].reverse().sort((a,b)=>b.at.localeCompare(a.at)).find(m=>m[key]!==null);return `<div class="metric"><small>${name}</small><strong>${latest?latest[key]:'—'}<span> ${unit}</span></strong><small>${latest?fmt(latest.at):'まだ記録なし'}</small></div>`;}
function workoutButtons(day){return ['quick','strength'].map(type=>{const done=completed(state,day,type),due=planned(state,day,type);return `<div class="row"><div><h3>${typeNames[type]}</h3><small>${done?'記録済み':due?'今日の予定':'予定休息日'}${type==='strength'?' · 週2回が基本':''}</small></div><button data-workout="${type}" data-day="${day}" class="${done?'':'primary'}">${done?'✓ 取消':'完了を記録'}</button></div>`;}).join('');}
function homeScreen(){const a=adherence(state),month=dateKey().slice(0,7),count=['front','side','back'].filter(view=>state.photos.some(p=>p.view===view&&p.at.startsWith(month))).length;
 app.innerHTML=title(dateKey().replaceAll('-',' / '),'今日の積み重ね')+`<div class="dashboard"><section class="card hero"><div class="row"><h2>身体の記録</h2><span class="pill">1年かけて、ゆっくり</span></div><div class="metrics">${metric('体重','weight','kg')}${metric('体脂肪率','fat','%')}${metric('腹囲','waist','cm')}</div><div class="goal">目標 ${state.settings.targetWeight} kg前後を維持 / 体脂肪率 ${state.settings.targetFat}%</div><button class="lime wide" data-go="measure">今日の数値を記録する ＋</button></section><section class="card"><h2>今日の運動</h2><div class="stack">${workoutButtons(dateKey())}</div></section></div><div class="grid"><section class="card"><small>直近28日の継続率</small><div class="count">${a.rate===null?'—':a.rate}<span style="font-size:18px">${a.rate===null?'':'%'}</span></div><small>予定 ${a.due} 回のうち ${a.done} 回完了</small></section><section class="card"><small>今月の定点写真</small><div class="count">${count}<span style="font-size:18px"> / 3</span></div><button data-go="photos">写真を撮る →</button></section></div><div class="notice">数値も写真も、この端末のこのアプリに保存されます。月に一度、設定から写真を含むバックアップを「ファイル」に保存しましょう。</div>`;
 bindWorkout();document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));}
function bindWorkout(){document.querySelectorAll('[data-workout]').forEach(b=>b.onclick=()=>guarded(async()=>{const day=b.dataset.day,type=b.dataset.workout;await commit(s=>{const found=s.workouts.find(w=>w.day===day&&w.type===type);if(found?.training&&(found.training.exercises.length||found.training.note)&&!confirm('完了を取り消すと、この日の筋トレ内容も削除します。続けますか？'))return s;if(found)s.workouts=s.workouts.filter(w=>w.id!==found.id);else s.workouts.push({id:crypto.randomUUID(),day,type,at:day===dateKey()?localTime():`${day}T18:00`});return s;});toast('運動記録を更新しました。');}));}
function chart(key){const points=[...state.measurements].filter(m=>m[key]!==null).sort((a,b)=>a.at.localeCompare(b.at));if(points.length<2)return '<p class="empty">2件以上の記録で推移グラフが表示されます。</p>';
 const values=points.map(p=>p[key]),min=Math.min(...values),max=Math.max(...values),pad=Math.max((max-min)*.2,.5),lo=min-pad,hi=max+pad,start=+new Date(points[0].at),end=+new Date(points.at(-1).at);
 const xy=points.map((p,i)=>[48+((end===start?i/(points.length-1):(+new Date(p.at)-start)/(end-start))*510),145-(p[key]-lo)/(hi-lo)*120]);
 return `<svg class="chart" viewBox="0 0 600 190" role="img" aria-label="${{weight:'体重',fat:'体脂肪率',waist:'腹囲'}[key]}の推移。最初 ${values[0]}、最新 ${values.at(-1)}"><path d="M48 25V145H558" stroke="#dae1d4" fill="none"/><text x="4" y="30" font-size="12" fill="#65746b">${hi.toFixed(1)}</text><text x="4" y="145" font-size="12" fill="#65746b">${lo.toFixed(1)}</text><polyline points="${xy.map(p=>p.join(',')).join(' ')}" stroke="#537b31" stroke-width="3" fill="none"/>${xy.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="4" fill="#123e36"><title>${fmt(points[i].at)}: ${values[i]}</title></circle>`).join('')}<text x="48" y="178" font-size="12" fill="#65746b">${points[0].at.slice(0,10)}</text><text x="558" y="178" text-anchor="end" font-size="12" fill="#65746b">${points.at(-1).at.slice(0,10)}</text></svg>`;}
function measureScreen(){app.innerHTML=title('BODY LOG','身体を記録する','測れる項目だけで大丈夫。同じ時間帯での記録がおすすめです。')+`<form id="measure-form" class="card"><label>測定日時<input name="at" type="datetime-local" value="${localTime()}" max="${localTime()}" required></label><div class="grid"><label>体重（kg）<input name="weight" type="number" inputmode="decimal" min="20" max="300" step="0.1" placeholder="未入力"></label><label>体脂肪率（%）<input name="fat" type="number" inputmode="decimal" min="1" max="70" step="0.1" placeholder="未入力"></label></div><label>腹囲（cm）<input name="waist" type="number" inputmode="decimal" min="30" max="250" step="0.1" placeholder="未入力"></label><button class="primary wide">記録を保存</button></form><section class="card"><div class="row"><h2>身体の推移</h2><select id="chart-type" aria-label="グラフの項目" style="width:auto"><option value="weight">体重 kg</option><option value="fat">体脂肪率 %</option><option value="waist">腹囲 cm</option></select></div><div id="chart">${chart('weight')}</div></section><section class="card"><h2>測定履歴 · ${state.measurements.length}件</h2>${state.measurements.length?[...state.measurements].reverse().sort((a,b)=>b.at.localeCompare(a.at)).map(m=>`<div class="history row"><div><small>${fmt(m.at)}</small><p>${[['weight','kg'],['fat','%'],['waist','cm']].filter(([k])=>m[k]!==null).map(([k,u])=>`${{weight:'体重',fat:'体脂肪率',waist:'腹囲'}[k]} ${m[k]} ${u}`).join(' / ')}</p></div><button data-remove-measure="${escape(m.id)}" class="danger">削除</button></div>`).join(''):'<p class="empty">記録はまだありません。実際に測った値から始めましょう。</p>'}</section>`;
 $('#measure-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);guarded(async()=>{const at=f.get('at');if(!isTime(at)||at>localTime())throw new Error('測定日時は現在以前を指定してください。');const m={id:crypto.randomUUID(),at};for(const key of ['weight','fat','waist'])m[key]=f.get(key)===''?null:Number(f.get(key));if(['weight','fat','waist'].every(k=>m[k]===null))throw new Error('測定した値を1つ以上入力してください。');await commit(s=>{s.measurements.push(m);return s;});toast('測定記録を保存しました。');});};$('#chart-type').onchange=e=>$('#chart').innerHTML=chart(e.target.value);
 document.querySelectorAll('[data-remove-measure]').forEach(b=>b.onclick=()=>guarded(async()=>{if(confirm('この測定記録を削除しますか？'))await commit(s=>{s.measurements=s.measurements.filter(m=>m.id!==b.dataset.removeMeasure);return s;});}));}
function exerciseScreen(){const a=adherence(state),total=state.workouts.length;app.innerHTML=title('MOVE & REST','運動と休息','予定の日を積み重ねる。休む日も、計画のうち。')+`<section class="card"><div class="row"><div><small>直近28日の継続率</small><div class="count">${a.rate===null?'—':a.rate+'%'}</div></div><div><strong>${a.done} / ${a.due}回</strong><p class="muted">${a.streak} 予定日連続達成</p></div></div><p class="notice">予定休息日は分母に含みません。今日の未完了予定は継続率に含み、連続達成は今日の途中でも途切れません。予定外の運動は履歴に残ります。</p><div class="grid"><div class="badge">${total>=1?'✓':'○'} はじめの一歩<br><small>初めての運動記録</small></div><div class="badge">${a.streak>=7?'✓':'○'} 7予定日達成<br><small>予定のある日を連続で完了</small></div><div class="badge">${total>=30?'✓':'○'} 積み重ね30回<br><small>運動記録30回</small></div><div class="badge">${a.rate===100&&a.due>=7?'✓':'○'} 28日パーフェクト<br><small>予定7回以上・完了率100%</small></div></div></section><section class="card"><h2>日付を選んでワンタップ記録</h2><label>運動日<input id="workout-day" type="date" required value="${dateKey()}" max="${dateKey()}" min="2000-01-01"></label><div id="workout-actions" class="stack">${workoutButtons(dateKey())}</div><small>過去日の記録時刻は18:00として保存します。</small></section><section class="card" id="training-editor"></section><section class="card" id="training-comparison"></section><section class="card"><h2>運動履歴 · ${total}回</h2>${total?[...state.workouts].sort((a,b)=>b.at.localeCompare(a.at)).map(w=>`<div class="history row"><div><small>${fmt(w.at)}</small><p>${typeNames[w.type]}</p>${w.training?`<p>${w.training.exercises.map(e=>escape(trainingText(e))).join("<br>")}</p>${w.training.note?`<p>${escape(w.training.note)}</p>`:""}`:""}${w.type==="strength"?`<button data-edit-training="${w.day}">内容を編集</button>`:""}</div><button class="danger" data-remove-workout="${escape(w.id)}">削除</button></div>`).join(''):'<p class="empty">まだ記録がありません。</p>'}</section>`;bindWorkout();trainingEditor(dateKey());trainingComparison();document.querySelectorAll('[data-edit-training]').forEach(b=>b.onclick=()=>{const day=b.dataset.editTraining;$('#workout-day').value=day;$('#workout-actions').innerHTML=workoutButtons(day);bindWorkout();trainingEditor(day);$('#training-editor').scrollIntoView({block:'start',behavior:'smooth'});});$('#workout-day').onchange=e=>{if(e.target.checkValidity()){ $('#workout-actions').innerHTML=workoutButtons(e.target.value);bindWorkout();trainingEditor(e.target.value);}};document.querySelectorAll('[data-remove-workout]').forEach(b=>b.onclick=()=>guarded(async()=>{if(confirm('この運動記録を削除しますか？'))await commit(s=>{s.workouts=s.workouts.filter(w=>w.id!==b.dataset.removeWorkout);return s;});}));}
function trainingText(e){return `${e.name} · ${e.sets}セット × ${e.reps}回 · ${e.weight===null?'重さ未記録':e.weight===0?'自重':e.weight+' kg'}`;}
function trainingEditor(day){
 const current=state.workouts.find(w=>w.day===day&&w.type==='strength'),previous=priorTraining(state.workouts,day);
 $('#training-editor').innerHTML=`<h2>筋トレの内容 · ${escape(day)}</h2><p class="muted">入力は任意です。1種目ごとのセット数と1セットあたりの回数を記録します。セットごとの違いはメモへ。重さは空欄なら未記録、0なら自重です。</p><form id="training-form"><div id="training-rows"></div><button id="add-exercise" type="button">種目を追加 ＋</button> ${previous?'<button id="copy-training" type="button">前回の内容を入力欄にコピー</button>':''}<label>メモ<textarea id="training-note" maxlength="1000" rows="3" placeholder="姿勢や、セットごとの回数など"></textarea></label><button class="primary wide">内容を保存して筋トレ完了</button><small>保存すると、この日の筋トレ完了も記録します。コピーだけでは保存されません。</small></form>`;
 const add=(e={name:'',sets:'',reps:'',weight:null})=>{
  if($('#training-rows').children.length>=30){toast('種目は30個までです。');return;}
  const row=document.createElement('div');row.className='training-row';row.innerHTML=`<label>種目名<input data-field="name" maxlength="80" required placeholder="例：スクワット" value="${escape(e.name)}" list="exercise-names"></label><div class="grid"><label>セット数<input data-field="sets" type="number" inputmode="numeric" min="1" max="100" step="1" required value="${e.sets}"></label><label>1セットの回数<input data-field="reps" type="number" inputmode="numeric" min="1" max="1000" step="1" required value="${e.reps}"></label></div><label>重さ（kg・任意）<input data-field="weight" type="number" inputmode="decimal" min="0" max="1000" step="0.1" placeholder="未記録（自重は0）" value="${e.weight??''}"></label><button type="button" class="danger">この種目を外す</button>`;
  row.querySelector('button').onclick=()=>row.remove();$('#training-rows').append(row);
 };
 const names=[...new Set(state.workouts.flatMap(w=>w.training?.exercises.map(e=>e.name)||[]))];const list=document.createElement('datalist');list.id='exercise-names';list.innerHTML=names.map(n=>`<option value="${escape(n)}"></option>`).join('');$('#training-form').append(list);
 const fill=t=>{$('#training-rows').innerHTML='';(t?.exercises.length?t.exercises:[undefined]).forEach(e=>add(e));$('#training-note').value=t?.note||'';};fill(current?.training);
 $('#add-exercise').onclick=()=>add();if(previous)$('#copy-training').onclick=()=>{if(confirm(`${previous.day}の内容で入力欄を置き換えますか？今回の実績に直してから保存してください。`))fill(previous.training);};
 $('#training-form').onsubmit=e=>{e.preventDefault();guarded(async()=>{
  const exercises=[...document.querySelectorAll('.training-row')].map(row=>{const get=k=>row.querySelector(`[data-field="${k}"]`).value;return {name:get('name'),sets:Number(get('sets')),reps:Number(get('reps')),weight:get('weight')===''?null:Number(get('weight'))};});
  const training=cleanTraining({exercises,note:$('#training-note').value});if(!exercises.length&&!training.note)throw new Error('種目かメモを入力してください。ワンタップ記録だけでも使えます。');
  await commit(s=>{let w=s.workouts.find(w=>w.day===day&&w.type==='strength');if(!w){w={id:crypto.randomUUID(),day,type:'strength',at:day===dateKey()?localTime():`${day}T18:00`};s.workouts.push(w);}w.training=training;return s;});toast('筋トレ内容を保存しました。');
 });};
}
function trainingComparison(){
 const sessions=state.workouts.filter(w=>w.type==='strength'&&w.training?.exercises.length).sort((a,b)=>b.day.localeCompare(a.day));
 const box=$('#training-comparison');box.innerHTML='<h2>筋トレ内容を比較</h2>'+(sessions.length?`<div class="grid">${['current','previous'].map((key,i)=>`<label>${i?'比較する記録':'今回の記録'}<select id="training-${key}">${sessions.map((w,n)=>`<option value="${escape(w.id)}" ${n===Math.min(i,sessions.length-1)?'selected':''}>${w.day}</option>`).join('')}</select></label>`).join('')}</div><div id="training-diff"></div><small>同じ種目名で比較します。差は「今回 − 比較する記録」。空欄の重さは比較しません。</small>`:'<p class="empty">筋トレ内容を保存すると、記録を選んで比較できます。</p>');
 if(!sessions.length)return;
 const update=()=>{const c=sessions.find(w=>w.id===$('#training-current').value),p=sessions.find(w=>w.id===$('#training-previous').value),delta=(v,u)=>v===null?'—':`${v>0?'+':''}${Number(v.toFixed(1))}${u}`;$('#training-diff').innerHTML=c.id===p.id?'<p class="empty">比較には別の日の記録を選んでください。</p>':compareTraining(c,p).map(d=>`<div class="history"><strong>${escape(d.current.name)}</strong><p>今回：${escape(trainingText(d.current))}</p><p>比較：${d.previous?escape(trainingText(d.previous)):'この種目の記録なし'}</p>${d.previous?`<small>差：セット ${delta(d.sets,'')} / 回数 ${delta(d.reps,'')} / 重さ ${delta(d.weight,' kg')}</small>`:''}</div>`).join('');};$('#training-current').onchange=update;$('#training-previous').onchange=update;update();
}
function photosScreen(){const photos=[...state.photos].reverse().filter(p=>p.view===photoView).sort((a,b)=>b.at.localeCompare(a.at)),previous=photos[0];compareIds=compareIds.filter(id=>photos.some(p=>p.id===id));if(compareIds.length!==2)compareIds=photos.slice(0,2).reverse().map(p=>p.id);
 app.innerHTML=title('MONTHLY CHECK','写真で変化を見る','月に一度、同じ場所・照明・距離で。正面、側面、背面を残しましょう。')+`<section class="card"><label>撮影方向<select id="photo-view">${Object.entries(viewNames).map(([v,n])=>`<option value="${v}" ${v===photoView?'selected':''}>${n}</option>`).join('')}</select></label><div class="camera"><video id="video" autoplay muted playsinline></video>${draft?`<img id="draft-preview" src="${photoURL(draft)}" alt="保存前の写真">`:previous?`<img id="overlay" src="${photoURL(previous)}" alt="前回写真のガイド" style="opacity:0.35">`:''}<div class="guide"></div></div><p id="camera-status" class="muted">${draft?'写真を確認してから保存してください。':previous?`ガイド: ${fmt(previous.at)}。カメラ開始後に重ね合わせます。`:'カメラを開始すると、ここに映ります。'}</p>${draft?`<label>撮影日時<input id="photo-at" type="datetime-local" value="${draft.at}" max="${localTime()}" required></label><div class="grid"><button id="save-photo" class="primary">この写真を保存</button><button id="discard-photo">撮り直す</button></div>`:`${previous?'<label>前回写真の濃さ<input id="opacity" type="range" min="0" max="80" value="35"></label>':''}<div class="grid"><button id="start-camera" class="primary">カメラを開始</button><button id="capture" disabled>撮影する</button></div><div class="grid"><label>カメラ<select id="facing"><option value="environment">背面カメラ</option><option value="user">前面カメラ</option></select></label><label>撮影タイマー<select id="delay"><option value="0">すぐに</option><option value="3">3秒</option><option value="10">10秒</option></select></label></div><button id="stop-camera" class="wide">カメラを停止</button><label class="file-button">カメラが使えないとき: 写真を選ぶ<input id="photo-file" type="file" accept="image/*" capture="environment"></label>`}<p class="notice">音声は使いません。写真はJPEGに変換して位置情報などの元画像メタデータを除き、端末内だけに保存します。画面を離れるとカメラを停止します。前面カメラも鏡像反転せずに保存します。</p></section><section class="card"><h2>2枚を左右で比較 · ${viewNames[photoView]}</h2>${photos.length>=2?`<div class="grid">${[0,1].map(i=>`<label>${i?'右':'左'}の写真<select id="compare-${i}">${photos.map((p,n)=>`<option value="${escape(p.id)}" ${compareIds[i]===p.id?'selected':''}>${fmt(p.at)} (${photos.length-n})</option>`).join('')}</select></label>`).join('')}</div><div id="compare-images"></div>`:'<p class="empty">同じ方向の写真が2枚そろうと比較できます。</p>'}</section><section class="card"><h2>写真履歴 · ${viewNames[photoView]} ${photos.length}枚</h2><div class="photo-grid">${photos.map(p=>`<div><img class="thumb" src="${photoURL(p)}" alt="${viewNames[p.view]} ${fmt(p.at)}" loading="lazy"><small>${fmt(p.at)}</small><button data-remove-photo="${escape(p.id)}" class="danger wide">削除</button></div>`).join('')}</div>${photos.length?'':'<p class="empty">写真はまだありません。</p>'}</section>`;
 $('#photo-view').onchange=e=>{stopCamera();draft=null;photoView=e.target.value;render();};
 if(draft){$('#save-photo').onclick=()=>guarded(async()=>{const at=$('#photo-at').value;if(!isTime(at)||at>localTime())throw new Error('撮影日時は現在以前を指定してください。');const p={...draft,id:crypto.randomUUID(),at,view:photoView};await commit(s=>{s.photos.push(p);return s;});draft=null;render();toast('写真を端末内に保存しました。');});$('#discard-photo').onclick=()=>{draft=null;render();};}
 else {$('#start-camera').onclick=()=>guarded(startCamera);$('#stop-camera').onclick=()=>{stopCamera();$('#capture').disabled=true;$('#camera-status').textContent='カメラを停止しました。';};$('#capture').onclick=()=>captureWithTimer();$('#facing').onchange=()=>{stopCamera();$('#capture').disabled=true;$('#camera-status').textContent='カメラを切り替えました。開始を押してください。';};if($('#opacity'))$('#opacity').oninput=e=>$('#overlay').style.opacity=e.target.value/100;$('#photo-file').onchange=e=>guarded(async()=>{const file=e.target.files[0];if(!file)return;if(file.size>30*1024*1024)throw new Error('写真は30MB以下を選んでください。');stopCamera();draft={...await normalizeImage(file),at:localTime()};render();});}
 if(photos.length>=2){const update=()=>{compareIds=[$('#compare-0').value,$('#compare-1').value];$('#compare-images').innerHTML=`<div class="compare">${compareIds.map(id=>{const p=photos.find(p=>p.id===id);return `<figure style="margin:0"><img src="${photoURL(p)}" alt="${viewNames[p.view]} ${fmt(p.at)}"><figcaption><small>${fmt(p.at)}</small></figcaption></figure>`;}).join('')}</div>`;};$('#compare-0').onchange=update;$('#compare-1').onchange=update;update();}
 document.querySelectorAll('.camera img,.thumb,#compare-images img').forEach(img=>img.onerror=()=>{if(!img.isConnected||tab!=='photos')return;img.alt='写真を読み込めません';if(!$('#photo-read-error')){const note=document.createElement('p');note.id='photo-read-error';note.className='notice';note.textContent='写真を表示できません。アプリを閉じて開き直し、もう一度確認してください。写真は自動削除しません。開き直しても読めない場合は、設定の救出機能で先に記録を保存できます。';app.prepend(note);}});document.querySelectorAll('[data-remove-photo]').forEach(b=>b.onclick=()=>guarded(async()=>{if(confirm('この写真を端末内から削除しますか？')){stopCamera();await commit(s=>{s.photos=s.photos.filter(p=>p.id!==b.dataset.removePhoto);return s;});}}));}
async function startCamera(){stopCamera();if(!isSecureContext||!navigator.mediaDevices?.getUserMedia)throw new Error('カメラはHTTPS、またはPCのlocalhostで使えます。写真選択も利用できます。');const token=cameraToken;let acquired;try{const supported=navigator.mediaDevices.getSupportedConstraints?.()||{};const videoConstraints={facingMode:{ideal:$('#facing').value}};if(supported.resizeMode)videoConstraints.resizeMode={ideal:'none'};acquired=await navigator.mediaDevices.getUserMedia({video:videoConstraints,audio:false});if(token!==cameraToken||tab!=='photos'){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;const track=stream.getVideoTracks()[0];const capabilities=track.getCapabilities?.()||{};if(Number.isFinite(capabilities.zoom?.min)){try{await track.applyConstraints({advanced:[{zoom:capabilities.zoom.min}]});}catch{/* Optional: keep the native camera view when zoom cannot be changed. */}}if(token!==cameraToken||tab!=='photos'){acquired.getTracks().forEach(t=>t.stop());return;}$('#video').srcObject=stream;await $('#video').play();$('#capture').disabled=false;$('#camera-status').textContent='映像全体を表示しています。頭と足が入る距離に置き、前回の姿勢に合わせてください。';}catch(e){if(acquired)acquired.getTracks().forEach(t=>t.stop());stream=null;if(token===cameraToken&&tab==='photos')$('#camera-status').textContent='カメラを開始できませんでした。';throw new Error(e.name==='NotAllowedError'?'カメラの利用が許可されていません。Safariのサイト設定で許可し、再試行してください。写真選択も使えます。':'カメラが見つからないか使用中です。再試行、または写真を選択してください。');}}
function captureWithTimer(){if(!stream||timer)return;let remaining=Number($('#delay').value);$('#capture').disabled=true;const capture=()=>guarded(async()=>{const video=$('#video');if(!video?.videoWidth)throw new Error('映像の準備ができていません。カメラを再開してください。');draft={...await canvasImage(video,video.videoWidth,video.videoHeight),at:localTime()};stopCamera();render();});if(!remaining){capture();return;}$('#camera-status').textContent=`あと ${remaining} 秒`;timer=setInterval(()=>{remaining--;if(remaining<=0){clearInterval(timer);timer=null;capture();}else $('#camera-status').textContent=`あと ${remaining} 秒`;},1000);}
async function canvasImage(source,width,height){const scale=Math.min(1,1600/Math.max(width,height));const c=document.createElement('canvas');c.width=Math.round(width*scale);c.height=Math.round(height*scale);c.getContext('2d').drawImage(source,0,0,c.width,c.height);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/jpeg',.85));if(!blob)throw new Error('写真の変換に失敗しました。');await photoData(blob);return {blob,width:c.width,height:c.height};}
async function inspectJPEG(blob){const bytes=new Uint8Array(await blob.slice(0,3).arrayBuffer());if(bytes[0]!==255||bytes[1]!==216||bytes[2]!==255)throw new Error('写真の形式が不正です。');const url=URL.createObjectURL(blob);try{const img=new Image();img.src=url;await img.decode();return {width:img.naturalWidth,height:img.naturalHeight};}finally{URL.revokeObjectURL(url);}}
async function normalizeImage(blob){const url=URL.createObjectURL(blob);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>60000000)throw new Error('画像が大きすぎます。縮小した写真を選んでください。');return await canvasImage(img,img.naturalWidth,img.naturalHeight);}catch{throw new Error('写真を読み込めません。JPEGまたはPNGで保存してから選んでください。');}finally{URL.revokeObjectURL(url);}}
function days(type,values){return `<div class="days">${dayNames.map((n,i)=>`<label><input type="checkbox" name="${type}" value="${i}" ${values.includes(i)?'checked':''}>${n}</label>`).join('')}</div>`;}
function settingsScreen(){const p=planAt(state,dateKey())||state.settings.plans.at(-1);app.innerHTML=title('YOUR SPACE · 1.1.0','設定とバックアップ')+`<section class="card"><h2>あなたの目標</h2><p class="muted">47歳男性 / 約1年で体重を維持しながら体脂肪率を15%へ。開始時の62kg・約20%は参考情報で、測定履歴には保存していません。</p><form id="settings-form"><div class="grid"><label>目標体重（kg）<input name="targetWeight" type="number" min="20" max="300" step="0.1" value="${state.settings.targetWeight}" required></label><label>目標体脂肪率（%）<input name="targetFat" type="number" min="1" max="70" step="0.1" value="${state.settings.targetFat}" required></label></div><h3>夕食前の簡易運動の予定</h3>${days('quick',p.quick)}<h3>筋トレの予定（初期設定: 火・金）</h3>${days('strength',p.strength)}<p class="notice">チェックのない曜日は予定休息日です。予定変更は今日から反映し、昨日以前の継続率はその日の予定で計算します。</p><button class="primary wide">目標と予定を保存</button></form></section><section class="card"><h2>データを守る</h2><p>記録・写真・設定をまとめたバックアップを保存できます。復元すると、現在の全データを置き換えます。</p><p><small>最後の書き出し操作: ${state.settings.lastBackup?fmt(state.settings.lastBackup):'まだありません'}</small></p><div class="stack"><button id="export" class="primary">全データと写真を書き出す</button><div id="backup-ready"></div><button id="export-readable">読める写真と記録を救出</button><button id="export-records">写真なしで記録を救出</button><small>写真が読み込めないとき、数値・運動・設定だけを別ファイルに保存できます。</small><label>バックアップを読み込んで復元<input id="import" type="file" accept=".json,application/json"></label></div><div id="storage" class="notice">保存容量を確認しています…</div><button id="persist" class="wide">データ保持をブラウザに依頼</button><p class="notice">写真や記録は外部送信しません。端末のロックを使ってプライバシーを守ってください。サイトデータの消去、アプリ削除、端末の故障・容量不足などで記録が失われることがあります。データ保持の依頼は保存を保証しません。書き出しファイルには身体写真が含まれ、暗号化されません。「ファイル」への保存先にも注意してください。</p></section><section class="card"><h2>iPhoneで使う</h2><p>HTTPSのURLをSafariで開き、共有メニューから「ホーム画面に追加」。追加後のアプリで記録を始めてください。通知はiPhoneの「時計」で曜日と時間を設定します。</p><p id="offline-status" class="notice">オフライン対応を確認しています…</p><button id="check-update">更新を確認する</button><p class="muted">更新がある場合は、アプリの画面をすべて閉じて開き直してください。</p></section>`;
 $('#settings-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);guarded(async()=>{await commit(s=>{s.settings.targetWeight=Number(f.get('targetWeight'));s.settings.targetFat=Number(f.get('targetFat'));const next={from:dateKey(),quick:f.getAll('quick').map(Number),strength:f.getAll('strength').map(Number)};const old=planAt(s,dateKey());if(!old||JSON.stringify(old.quick)!==JSON.stringify(next.quick)||JSON.stringify(old.strength)!==JSON.stringify(next.strength)){s.settings.plans=s.settings.plans.filter(p=>p.from!==dateKey());s.settings.plans.push(next);s.settings.plans.sort((a,b)=>a.from.localeCompare(b.from));}return s;});toast('目標と予定を保存しました。');});};
 $('#export').onclick=()=>guarded(()=>exportBackup(false));$('#export-records').onclick=()=>guarded(()=>exportBackup(true));$('#export-readable').onclick=()=>guarded(()=>exportBackup(false,true));showPreparedBackup();$('#import').onchange=e=>{const file=e.target.files[0];if(file)guarded(()=>importBackup(file));};$('#persist').onclick=()=>guarded(async()=>{const granted=await navigator.storage?.persist?.();toast(granted?'ブラウザがデータ保持の依頼を受け付けました。バックアップも続けてください。':'データ保持は許可されませんでした。バックアップを保存してください。');await storageInfo();});$('#check-update').onclick=()=>guarded(async()=>{const r=await navigator.serviceWorker?.getRegistration();if(r){await r.update();toast(r.waiting?'更新があります。すべてのアプリ画面を閉じて開き直してください。':'更新を確認しました。');}else toast('オフライン対応が未完了です。HTTPSでオンライン再読み込みしてください。');});storageInfo();offlineInfo();}
async function storageInfo(){if(!$('#storage'))return;const estimated=await navigator.storage?.estimate?.(),persistent=await navigator.storage?.persisted?.(),photoSize=state.photos.reduce((n,p)=>n+p.blob.size,0);if($('#storage'))$('#storage').textContent=`写真 ${state.photos.length}枚 / ${(photoSize/1024/1024).toFixed(1)} MB。${estimated?.quota?`このサイトの使用量 約${(estimated.usage/1024/1024).toFixed(1)} MB / 上限目安 ${(estimated.quota/1024/1024).toFixed(0)} MB。`:'ブラウザから容量情報を取得できません。'} データ保持: ${persistent?'許可済み':'保証なし'}。容量は端末とブラウザで変わります。`;}
async function offlineInfo(){const r=await navigator.serviceWorker?.getRegistration();if($('#offline-status'))$('#offline-status').textContent=r?.active?'オフライン準備完了。初回はオンラインで開き、次から通信なしでも使えます。':'オフライン準備中、またはHTTPS以外で開いています。オンラインで再読み込みして確認してください。';}
function clearPreparedBackup(){if(backupDownloadURL)URL.revokeObjectURL(backupDownloadURL);backupDownloadURL=null;preparedBackup=null;}
function showPreparedBackup(){const box=$('#backup-ready');if(!box||!preparedBackup)return;const p=preparedBackup;const sharable=canSaveViaShare(p.file);box.innerHTML=`<div class="notice"><strong>${p.recordsOnly?'写真なしの救出ファイル':p.partial?'読める写真だけの救出ファイル':'写真込みのバックアップ'}を準備しました</strong><p>測定 ${p.counts.measurements}件 / 運動 ${p.counts.workouts}回 / 写真 ${p.counts.photos}枚<br>${(p.file.size/1024/1024).toFixed(2)} MB</p><p>${p.recordsOnly?'このファイルには写真が含まれません。復元すると現在の写真も置き換わるため、元のアプリを消さずに保管してください。':'iPhoneでは「ファイルに保存する」を押し、開いたメニューで「ファイルに保存」を選んでください。'}</p>${p.partial?`<p>読み込めない写真 ${p.missingPhotos.length}枚は含まれません。元の写真は削除していません。この救出ファイルを復元すると現在の全写真を置き換えます。</p>`:''}<div class="stack">${sharable?'<button id="backup-share" class="primary">ファイルに保存する</button>':''}<a class="file-button" id="backup-download" download="${escape(p.file.name)}">ダウンロードで保存</a><button id="backup-confirm">ファイルへの保存を確認した</button></div><p id="backup-save-status">保存先のファイルが存在することを確認してください。準備だけではバックアップ保存は完了していません。</p></div>`;if(sharable)$('#backup-share').onclick=()=>guarded(async()=>{try{await sharePreparedFile(p);if($('#backup-save-status'))$('#backup-save-status').textContent='「ファイル」に保存されていることを確認して、下の確認ボタンを押してください。';}catch(e){if(e.name==='AbortError'){toast('保存を取り消しました。準備済みファイルから再試行できます。');return;}toast('保存メニューを開けませんでした。もう一度「ファイルに保存する」、またはダウンロードを試してください。');}});const link=$('#backup-download');link.href=backupDownloadURL;link.onclick=()=>{if($('#backup-save-status'))$('#backup-save-status').textContent='ダウンロード先にJSONファイルが保存されたことを確認してください。';};$('#backup-confirm').onclick=()=>guarded(async()=>{if(!confirm('「ファイル」にバックアップJSONが保存されていることを確認しましたか？'))return;const at=localTime();await saveBackupTime(at);state={...state,settings:{...state.settings,lastBackup:at}};clearPreparedBackup();render();toast('バックアップの保存確認を記録しました。');});}
async function exportBackup(recordsOnly=false,skipUnreadable=false){if(skipUnreadable&&!confirm('読み込めない写真は含めず、読める写真と数値・運動・設定を救出します。元データは削除しません。続けますか？'))return;stopCamera();clearPreparedBackup();const button=$(recordsOnly?'#export-records':skipUnreadable?'#export-readable':'#export');if(button){button.disabled=true;button.textContent='バックアップを準備しています…';}try{preparedBackup=await prepareBackup(state,localTime(),recordsOnly,skipUnreadable);backupDownloadURL=URL.createObjectURL(preparedBackup.file);if(tab==='settings'){showPreparedBackup();$('#backup-ready').scrollIntoView({block:'center',behavior:'smooth'});}toast('準備ができました。表示された保存ボタンを押してください。');}catch(e){if($('#backup-ready'))$('#backup-ready').textContent=e.message;throw e;}finally{if(button){button.disabled=false;button.textContent=recordsOnly?'写真なしで記録を救出':skipUnreadable?'読める写真と記録を救出':'全データと写真を書き出す';}}}
async function importBackup(file){if(file.size>150*1024*1024)throw new Error('初版で読み込めるバックアップは150MBまでです。');const raw=JSON.parse(await file.text());if(raw.app!=='BODY RECOMP')throw new Error('BODY RECOMPのバックアップを選んでください。');const clean=validateState(raw,true);const photos=[];for(const p of clean.photos){const bytes=Uint8Array.from(atob(p.data.split(',')[1]),c=>c.charCodeAt(0));const blob=new Blob([bytes],{type:'image/jpeg'});const image=await inspectJPEG(blob);if(image.width!==p.width||image.height!==p.height)throw new Error('写真サイズとバックアップの情報が一致しません。');const {data,...meta}=p;photos.push({...meta,blob});}clean.photos=photos;validateState(clean);if(!confirm(`${raw.backupNote?'このファイルは一部または全部の写真を含まない救出用です。現在の写真も置き換わります。\n':''}測定 ${clean.measurements.length}件、運動 ${clean.workouts.length}件、写真 ${clean.photos.length}枚で現在の全データを置き換えます。先に書き出しを保存しましたか？`))return;stopCamera();draft=null;await commit(()=>clean);toast('全データと写真を復元しました。');}
function navigate(next){if(next===tab)return;clearPreparedBackup();if(draft&&!confirm('保存前の写真を破棄して画面を移動しますか？'))return;stopCamera();draft=null;tab=next;render();window.scrollTo(0,0);}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.tab));
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopCamera();if($('#capture'))$('#capture').disabled=true;if($('#camera-status')&&!draft)$('#camera-status').textContent='カメラを停止しました。再開するには開始を押してください。';}else if(state&&!busy&&!stream&&!draft)guarded(async()=>{state=await readState();render();});});
window.addEventListener('pagehide',stopCamera);window.addEventListener('online',connection);window.addEventListener('offline',connection);
try{await openDB();state=await readState();render();if('serviceWorker'in navigator&&isSecureContext){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{if(tab==='settings')offlineInfo();}).catch(()=>toast('オフライン準備に失敗しました。オンラインで再読み込みしてください。'));}}catch(e){app.innerHTML=title('STORAGE','端末内保存を開始できません')+'<div class="card"><p>Safariの通常モードで開き直してください。サイトデータの消去は既存の記録を削除するため、バックアップがある場合だけ行ってください。</p><button id="retry">再読み込み</button></div>';$('#retry').onclick=()=>location.reload();toast(e.message);}
